name: CI
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  test:
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn install --frozen-lockfile
    - name: Build the source code
      run: yarn build
    - name: Test esbuild-server building
      run: ../bin/main.js build
      working-directory: examples
    - name: Test esbuild-server book building
      run: ../bin/main.js book --build
      working-directory: examples
