on:
  push:
    branches:
      - main

name: Publish packages to NPM
jobs:
  publish:
    runs-on: [self-hosted, dind-actions-runner]
    timeout-minutes: 25
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: false
    - name: Check, install and build
      run: |
        \. "$NVM_DIR/nvm.sh" && nvm use

        # Install dependencies
        echo "::group::Install"
        node common/scripts/install-run-rush.js install
        echo "::endgroup::"

        # Build with tests
        node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build:test --verbose
    - name: Run prerelease scripts
      run: |
        \. "$NVM_DIR/nvm.sh" && nvm use
        node common/scripts/install-run-rush.js prerelease
    - name: Publish latest to NPM
      run:  |
        \. "$NVM_DIR/nvm.sh" && nvm use

        # Publish under "latest" tag
        node common/scripts/install-run-rush.js publish --publish --include-all --tag latest
