on:
  push:
    branches:
      - main

name: Publish packages to NPM
jobs:
  publish:
    strategy:
      matrix:
        node: ['16.14']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install -g @microsoft/rush@5.58.0 pnpm@6.24.2 yarn@1.22.17
    - name: Build the source code and test
      run: node common/scripts/install-run-rush.js build:test --verbose
    - name: Publish latest to NPM
      run: node common/scripts/install-run-rush.js publish --publish --include-all --tag latest
